minVersion: 0.28.1
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: registry
    sdks:
      npm:@sentry/status-page-list:
  - name: github
