/**
 * This file is auto-generated by scripts/generateMapping.ts
 * Do not modify this file manually.
 *
 * Regenerate this file by running `yarn generate`
 */

/**
 * Mapping of domain to status page URL
 */
export const domainToStatusPageUrls = {
  "absurd.design": "https://status.absurd.design/",
  "adobe.com": "https://status.adobe.com/",
  "*.adobe.com": "https://status.adobe.com/",
  "akamai.com": "https://www.akamaistatus.com/",
  "*.akamai.com": "https://www.akamaistatus.com/",
  "amplitude.com": "https://status.amplitude.com/",
  "*.amplitude.com": "https://status.amplitude.com/",
  "*.apple.com": "https://developer.apple.com/system-status/",
  "api.apple.com": "https://developer.apple.com/system-status/",
  "*.appsflyer.com": "https://status.appsflyer.com/",
  "appsflyer.com": "https://status.appsflyer.com/",
  "*.atlassian.net": "https://status.atlassian.com/",
  "atlassian.net": "https://status.atlassian.com/",
  "atlassian.com": "https://status.atlassian.com/",
  "*.atlassian.com": "https://status.atlassian.com/",
  "*.bamboohr.com": "https://status.bamboohr.com/",
  "bamboohr.com": "https://status.bamboohr.com/",
  "*.box.com": "https://status.box.com/",
  "box.com": "https://status.box.com/",
  "cloudflare.com": "https://www.cloudflarestatus.com/",
  "*.cloudflare.com": "https://www.cloudflarestatus.com/",
  "codecov.io": "https://status.codecov.com/",
  "*.codecov.io": "https://status.codecov.com/",
  "crowdin.com": "https://status.crowdin.com/",
  "*.crowdin.com": "https://status.crowdin.com/",
  "datadoghq.com": "https://status.datadoghq.com/",
  "*.datadoghq.com": "https://status.datadoghq.com/",
  "datadoghq.eu": "https://status.datadoghq.eu/",
  "*.datadog.eu": "https://status.datadoghq.eu/",
  "designmodo.com": "https://status.designmodo.com/",
  "*.designmodo.com": "https://status.designmodo.com/",
  "digitalocean.com": "https://status.digitalocean.com/",
  "*.digitalocean.com": "https://status.digitalocean.com/",
  "discord.com": "https://discordstatus.com/",
  "dropbox.com": "https://status.dropbox.com/",
  "github.com": "https://www.githubstatus.com",
  "*.github.com": "https://www.githubstatus.com",
  "github.io": "https://www.githubstatus.com",
  "*.github.io": "https://www.githubstatus.com",
  "googleapis.com": "https://status.cloud.google.com",
  "*.googleapis.com": "https://status.cloud.google.com",
  "sentry.io": "https://status.sentry.io/",
  "*.sentry.io": "https://status.sentry.io/",
  "*.slack.com": "https://slack-status.com/",
  "slack.com": "https://slack-status.com/",
};
