/**
 * This file is auto-generated by scripts/generateMapping.ts
 * Do not modify this file manually.
 *
 * Regenerate this file by running `yarn generate`
 */

/**
 * Mapping of domain to status page URL
 */
export const domainToStatusPageUrls = {};
