/**
 * This file is auto-generated by scripts/generateMapping.ts
 * Do not modify this file manually.
 *
 * Regenerate this file by running `yarn generate`
 */

export { absurdDesignStatusInfo } from "./absurd_design";
export { adobeStatusInfo } from "./adobe";
export { akamaiStatusInfo } from "./akamai";
export { amplitudeStatusInfo } from "./amplitude";
export { appleDeveloperStatusInfo } from "./apple_developer";
export { atlassianStatusInfo } from "./atlassian";
export { codecovStatusInfo } from "./codecov";
export { githubStatusInfo } from "./github";
export { googleCloudStatusInfo } from "./google_cloud";
export { sentryStatusInfo } from "./sentry";
export { slackStatusInfo } from "./slack";
