/**
 * This file is auto-generated by scripts/generateMapping.ts
 * Do not modify this file manually.
 *
 * Regenerate this file by running `yarn generate`
 */

export { absurdDesignStatusInfo } from "./absurd_design";
export { adobeStatusInfo } from "./adobe";
export { akamaiStatusInfo } from "./akamai";
export { amplitudeStatusInfo } from "./amplitude";
export { appleDeveloperStatusInfo } from "./apple_developer";
export { appsflyerStatusInfo } from "./appsflyer";
export { atlassianStatusInfo } from "./atlassian";
export { bambooHrStatusInfo } from "./bamboohr";
export { boxStatusInfo } from "./box";
export { cloudflareStatusInfo } from "./cloudflare";
export { codecovStatusInfo } from "./codecov";
export { crowdinStatusInfo } from "./crowdin";
export { datadogStatusInfo } from "./datadog";
export { datadogEUStatusInfo } from "./datadog_eu";
export { designmodoStatusInfo } from "./designmodo";
export { digitalOceanStatusInfo } from "./digitalocean";
export { discordStatusInfo } from "./discord";
export { dropboxStatusInfo } from "./dropbox";
export { githubStatusInfo } from "./github";
export { googleCloudStatusInfo } from "./google_cloud";
export { sentryStatusInfo } from "./sentry";
export { slackStatusInfo } from "./slack";
