name: Build and Test

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install node modules
        run: yarn install --frozen-lockfile

      - name: Build Package
        run: yarn build

      - name: Check types
        run: yarn typecheck

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Generate tarball artifact
        run: yarn pack

      - name: Upload artifact for release via getsentry/craft
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: ${{ github.workspace }}/*.tgz
          if-no-files-found: error
